male(anna).
male(chandu).
male(ganesh).
male(pinto).
male(ajey).
male(pradeep).
male(vijay).
male(kishor).
male(sankalp).
male(shubham).
male(sahil).
male(nilesh).
male(sai).


female(lata).
female(surekha).
female(asha).
female(aditi).
female(bai).
female(shweta).
female(jyoti).
female(karishma).
female(shrishti).
female(nidhi).
female(mrunali).
female(rutu).
female(surbhi).

parent(anna,chandu).
parent(anna,asha).
parent(lata,chandu).
parent(lata,asha).
parent(surekha,pinto).
parent(surekha,bai).
parent(surekha,nilesh).
parent(chandu,pinto).
parent(chandu,bai).
parent(chandu,nilesh).
parent(bai,sai).
parent(ajey,sai).
parent(ganesh,pradeep).
parent(ganesh,jyoti).
parent(ganesh,karishma).
parent(asha,pradeep).
parent(asha,jyoti).
parent(asha,karishma).
parent(shweta,shrishti).
parent(shweta,sankalp).
parent(pradeep,shrishti).
parent(pradeep,sankalp).
parent(jyoti,nidhi).
parent(jyoti,shubham).
parent(vijay,nidhi).
parent(vijay,shubham).
parent(karishma,sahil).
parent(karishma,mrunali).
parent(kishor,sahil).
parent(kishor,mrunali).
parent(nilesh,surbhi).
parent(rutu,surbhi).

wife(lata,anna).
wife(surekha,chandu).
wife(asha,ganesh).
wife(aditi,pinto).
wife(bai,ajey).
wife(shweta,pradeep).
wife(jyoti,vijay).
wife(karishma,kishor).
wife(rutu,nilesh).

mother(X,Y):-female(X),parent(X,Y).
father(X,Y):-male(X),parent(X,Y).
sibling(X,Y) :-parent(Z,X),parent(Z,Y),X\=Y.
grandparent(X,Y):-parent(X,Z),parent(Z,Y).
grandfather(X,Y):-male(X),parent(X,Z),parent(Z,Y).
grandmother(X,Y):-female(X),parent(X,Z),parent(Z,Y).

cousin(X,Y):-parent(A,Y),sibling(A,B),parent(B,X).
